functionsDirectory = "/Users/yaramohamed/Desktop/heilberuf/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "/Users/yaramohamed/Desktop/heilberuf"
publishOrigin = "config"
functions = "/Users/yaramohamed/Desktop/heilberuf/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"